services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    command: ${START_CMD}
    deploy:
      replicas: 1
      update_config:
        delay: 10s

    environment:
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_PROXY_HEADERS: xforwarded
      KC_HEALTH_ENABLED: true
      KC_HTTP_ENABLED: ${KEYCLOAK_HTTP_ENABLED}
      KC_PROXY: ${KEYCLOAK_PROXY}
      
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_SCHEMA: keycloak
      KC_DB_URL: ${POSTGRES_URL}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    volumes:
      - ./dist_keycloak:/opt/keycloak/providers/
    restart: unless-stopped